echo ' ---> Hello rr1testing scriptedit!!!!!!test'
echo ' ---> testingtest1!3test123test23test12tes2t4512312'
#sleep 5m


echo "-----> job triggeredBy"
echo JobTriggredByName=$JOB_TRIGGERED_BY_NAME
echo JobTriggredById=$JOB_TRIGGERED_BY_ID

echo "-----> runSh Job variables"
echo SUBSCRIPTION_ID=${#SUBSCRIPTION_ID}
echo CURRENT_JOB_NAME=$JOB_NAME
echo CURRENT_JOB_TYPE=$JOB_TYPE
echo CURRENT_JOB_RESOURCE_ID=$RESOURCE_ID
echo CURRENT_JOB_BUILD_ID=$BUILD_ID
echo CURRENT_JOB_BUILD_NUMBER=$BUILD_NUMBER
echo CURRENT_JOB_BUILD_JOB_ID=$BUILD_JOB_ID
echo CURRENT_JOB_BUILD_JOB_NUMBER=$BUILD_JOB_NUMBER
echo CURRENT_JOB_PATH=$JOB_PATH
echo CURRENT_JOB_STATE=$JOB_STATE
echo CURRENT_JOB_PREVIOUS_STATE=$JOB_PREVIOUS_STATE
echo CURRENT_JOB_MESSAGE_PATH=$JOB_MESSAGE
